future: true
permalink: /:title/
url: http://blog.xyecho.com
name: xyecho
author: xyecho
qq: 
email: 1447675994@gmail.com
duoshuo: xyecho
beian: 
cnzz: 
weibo: xyecho
github: xyecho
paginate: 20
highlighter: rouge
truncate: true
about: "xyecho(xyecho)"
