future: true
permalink: /:title/
url: http://blog.xyecho.com
name: xyecho
subtitle: 读书，技术，生活笔记
author: xyecho
email: 1447675994@qq.com
duoshuo: xyecho
beian: 
cnzz: 
weibo: 万盏风铃木
weibourl: https://weibo.com/u/1770097211
github: https://github.com/kakabei
paginate: 20
highlighter: rouge
truncate: true
about: "xyecho(xyecho)"
plugins: [jekyll-paginate]