future: true
permalink: /:title/
author_avatar: /images/header.png
url: "http://blog.xyecho.com"
github_site_repo: kakabei/kakabei.github.io
name: xyecho - just my notes
author: kane
qq: 
email: 1447675994@qq.com
beian: 
cnzz: 
weibo: 一铺路
github: kakabei/kakabei.github.io
paginate: 20
highlighter: rouge
truncate: true
about: "kane"
excerpt_separator: "<!-- more -->"