future: true
permalink: /:title/
url: "http://blog.xyecho.com"
name: xyecho - just my notes
author: kane
qq: 
email: 1447675994@qq.com
beian: 
cnzz: 
weibo: hustcat
github: kakabei/kakabei.github.io
paginate: 20
highlighter: rouge
truncate: true
about: "YY哥(hustcat)"
