# Site settings
title: xyecho - Reading, Life, Tech
author: carlos
author_avatar: /images/header.png
email: 1447675994@qq.com
description: 读书，生活，技术
url: "http://blog.xyecho.com"
domain: "xyecho.com"
#github_username: dongyado
github_site_repo: kakabei/kakabei.github.io
#disqus: xyecho


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    #extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "smart","strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]


sass:
    style: :compressed
    sass_dir: _sass

permalink: /:title
excerpt_separator: "<!-- more -->"

# path
categories_path: categories
tags_path: tags


gems:
  - jekyll-sitemap
